### ISSUE TITLE
How can I perform a demo test?

### ISSUE THREAD

**Issue by hulonghua-devin** [edz-o/3DNBF#1]
I'd like to use your pre-trained model to reconstruct videos and images. Could you please guide me on how to test this? I'm very grateful for your assistance.

**Comment by edz-o** [comment]
Hi, I just updated the [demo part](https://github.com/edz-o/3DNBF?tab=readme-ov-file#demo) to make it easier to follow. If you successfully install the project you should be able to run our demo directly. For running on your data, you just need to preprocess it into the same format used in the demo.

**Comment by hulonghua-devin** [comment]
Thanks, bro
