### ISSUE TITLE
disable_occ=True?

### ISSUE THREAD

**Issue by GloryyrolG** [edz-o/3DNBF#3]
Hi @edz-o et al.,

Thx for ur exellent work. May I ask it seems the `occ` model is never activated for all given configs, no? If I understood correctly, a Bernoulli is used to model occ? Any clarification would help! Thx in advance & best,

https://github.com/edz-o/3DNBF/blob/c0e2cdb991b64b852ea8c583d5bda47444d8ae04/mmhuman3d/models/losses/likelihood_loss.py#L93

As stated in the paper:
>  but note that we are using a robust likelihood during inference. (Sec. 3.2)

**Comment by edz-o** [comment]
Thanks for your interest in our work! You are right the `disable_occ` should be set to False. I've updated the configs.
