### ISSUE TITLE
2-Stage Impl?

### ISSUE THREAD

**Issue by GloryyrolG** [edz-o/3DNBF#5]
Hi @edz-o @Angtian @AdamKortylewski et al.,

It would be good if u could clarify where 2-stage is implemented in the current codebase. I have trouble localizing it. Thx!

<img width="473" alt="image" src="https://github.com/edz-o/3DNBF/assets/33202229/e99c2d4e-b20c-411d-9cb9-0cba6b6b4932">

**Comment by edz-o** [comment]
Thanks for your interest in our work! As mentioned in the paper, in the implementation we just convert pretrained SMPL to NBV for convenience.
