### ISSUE TITLE
NLL Loss?

### ISSUE THREAD

**Issue by GloryyrolG** [edz-o/3DNBF#6]
Hi @edz-o @Angtian @AdamKortylewski et al., 

Could u kindly provide hints on where the NLL loss is computed during training? The loss computation is a bit complicated, and I got confused. Thx!

<img width="478" alt="image" src="https://github.com/edz-o/3DNBF/assets/33202229/13d2bfb7-90b2-44b8-af9f-4d5f4aa46b63">

https://github.com/edz-o/3DNBF/blob/3f9e868c46c0f91b7a0f56ea9d19adda2a5b0bcf/mmhuman3d/models/losses/coke_loss.py#L464

**Comment by edz-o** [comment]
Sorry for the confusion. The sampling is implemented [here](https://github.com/edz-o/3DNBF/blob/3f9e868c46c0f91b7a0f56ea9d19adda2a5b0bcf/mmhuman3d/utils/image_utils.py#L382) which comes from the [VoGE repo](https://github.com/edz-o/VoGE-3DNBF).

**Comment by GloryyrolG** [comment]
Hi @edz-o, Thx for the instant clarification! Could u further point out where `z` is explicitly used during training? What I could see is that u use the rendered mask. Thx.

https://github.com/edz-o/3DNBF/blob/3f9e868c46c0f91b7a0f56ea9d19adda2a5b0bcf/mmhuman3d/models/architectures/mesh_estimator_se_voge.py#L1072

<img width="501" alt="image" src="https://github.com/edz-o/3DNBF/assets/33202229/d25552f1-d7b4-4f2a-bcc7-1bf844f3a9a4">

<img width="501" alt="image" src="https://github.com/edz-o/3DNBF/assets/33202229/c98afc4e-d409-46fa-954e-da851ca94418">

**Comment by edz-o** [comment]
The `z` variable is not used during training. We need the mask during training to learn the bg features.

**Comment by GloryyrolG** [comment]
Okay, so if I understood correctly,

1. `feature_bank.clutter_bank` for BG is trained with contrastive `coke_loss` instead:
https://github.com/edz-o/3DNBF/blob/3f9e868c46c0f91b7a0f56ea9d19adda2a5b0bcf/mmhuman3d/models/losses/coke_loss.py#L422
2. The inference of `z`:
https://github.com/edz-o/3DNBF/blob/3f9e868c46c0f91b7a0f56ea9d19adda2a5b0bcf/mmhuman3d/models/losses/likelihood_loss.py#L100
follows [CompositionalNets](https://github.com/AdamKortylewski/CompositionalNets)
<img width="725" alt="image" src="https://github.com/edz-o/3DNBF/assets/33202229/bacd2f5f-5720-4128-b5f3-2e964aab80d7">

3. What does this line mean, BG = rendered + GT mask?
https://github.com/edz-o/3DNBF/blob/3f9e868c46c0f91b7a0f56ea9d19adda2a5b0bcf/mmhuman3d/models/architectures/mesh_estimator_se_voge.py#L1074
Best,

**Comment by edz-o** [comment]
Yes, your understanding is correct. For 3, if we add any occlusion augmentation during training, we need to update the bg mask to include the occluded regions.

**Comment by GloryyrolG** [comment]
> We need the mask during training to learn the bg features.

&

> Yes, your understanding is correct. For 3, if we add any occlusion augmentation during training, we need to update the bg mask to include the occluded regions.

Hi @edz-o , I understood the mask is generated by the projection of the GT SMPL. Did u consider the natural occluder in the image itself, e.g., chair and pole, etc.? If so, how do u get corresponding masks? If not, did u consider adding syn patches on the top of the occluder in which way one could obtain the `occ_mask` then? Thx in advance,

**Comment by edz-o** [comment]
We didn't consider natural occluders and just randomly applied synthetic patches. It would be interesting to explore adding more natural occluders or to detect occluded regions.
