### ISSUE TITLE
human body model not displayed on demo results

### ISSUE THREAD

**Issue by Shan924** [edz-o/3DNBF#7]
Thanks for your excellent work.
When  I run the demo part, the result is like this:
![image](https://github.com/edz-o/3DNBF/assets/49831649/e6eb7dde-ccee-4f0e-9e84-50af0128bdce)

When I uncommented these two lines of code, and run this command `CUDA_VISIBLE_DEVICES=0 python tools/visualize_predictions.py --config configs/3dnbf/resnet50_pare_w_coke_pw3d_demo.py --output_file output/result_keypoints.json --outdir output/visualization
` again,  the result became like this:
https://github.com/edz-o/3DNBF/blob/3f9e868c46c0f91b7a0f56ea9d19adda2a5b0bcf/tools/visualize_predictions.py#L149-L150
![image](https://github.com/edz-o/3DNBF/assets/49831649/eb4b8c1e-f188-4763-805f-a0deac328d77)

I want to know why the human body model is not displayed on my demo results.
Thanks in advance.

**Comment by edz-o** [comment]
Hi, could you confirm that you are using PyTorch3D 0.4.0? For higher versions, the camera convention is different and it will break.

**Comment by Shan924** [comment]
I reconfigured the environment again, and this time I installed pytorch3d 0.4.0. The demo can be displayed normally. Thanks a lot.
